"""empty message

Revision ID: 9cd8616eb9f2
Revises: aeda9b6d8e84
Create Date: 2019-07-05 00:22:22.432527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd8616eb9f2'
down_revision = 'aeda9b6d8e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('events_creator_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['users_id'], ['id'])
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_creator_id_fkey', 'events', 'users', ['creator_id'], ['id'])
    op.drop_column('events', 'users_id')
    # ### end Alembic commands ###
