"""empty message

Revision ID: a0a7247225f1
Revises: edbbcb3a76c1
Create Date: 2019-07-02 12:08:54.103586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a7247225f1'
down_revision = 'edbbcb3a76c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating users',
    sa.Column('rater_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('target_user_id')
    )
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=90),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=90),
               existing_nullable=False)
    op.drop_table('rating users')
    # ### end Alembic commands ###
