"""empty message

Revision ID: a30c07c0a5ea
Revises: 0b92dc98065a
Create Date: 2019-07-07 00:08:48.381904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30c07c0a5ea'
down_revision = '0b92dc98065a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('about', sa.String(length=999), nullable=False))
    op.drop_column('profiles', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('description', sa.VARCHAR(length=999), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'about')
    # ### end Alembic commands ###
