"""empty message

Revision ID: b6e11fe4739a
Revises: e8a275a1e770
Create Date: 2019-07-03 23:10:33.653267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e11fe4739a'
down_revision = 'e8a275a1e770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('events_user_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['creator_id'], ['id'])
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_user_id_fkey', 'events', 'users', ['user_id'], ['id'])
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###
