"""empty message

Revision ID: c01ac34c1603
Revises: 6aa89f1cfceb
Create Date: 2019-07-03 15:50:28.255334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01ac34c1603'
down_revision = '6aa89f1cfceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(length=999), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
