"""empty message

Revision ID: cdf9744630a9
Revises: a0a7247225f1
Create Date: 2019-07-02 16:05:48.560708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9744630a9'
down_revision = 'a0a7247225f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_users',
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rater_id', 'target_user_id')
    )
    op.drop_table('rating users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=90),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=90),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.create_table('rating users',
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name='rating users_rater_id_fkey'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='rating users_target_user_id_fkey'),
    sa.PrimaryKeyConstraint('target_user_id', name='rating users_pkey')
    )
    op.drop_table('rating_users')
    # ### end Alembic commands ###
