"""empty message

Revision ID: d3d3dcaadc2b
Revises: 9cd8616eb9f2
Create Date: 2019-07-05 00:24:33.220621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d3dcaadc2b'
down_revision = '9cd8616eb9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('events_users_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['creator_id'], ['id'])
    op.drop_column('events', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_users_id_fkey', 'events', 'users', ['users_id'], ['id'])
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###
