"""empty message

Revision ID: d9963c760f35
Revises: a30c07c0a5ea
Create Date: 2019-07-07 00:27:01.152444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9963c760f35'
down_revision = 'a30c07c0a5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###
