"""empty message

Revision ID: e8a275a1e770
Revises: c01ac34c1603
Create Date: 2019-07-03 16:01:31.643866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8a275a1e770'
down_revision = 'c01ac34c1603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('events', 'image')
    op.drop_column('events', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'created')
    # ### end Alembic commands ###
